tomaj/nette-api

- src/model/ApiDecider.php
- src/model/link/ApiLink.php
- src/model/params/InputParam.php
- src/presenters/ApiPresenter.php
Chcel by som pridat akciu pre vypis endpointov, ktore su zaregistrovane.
Do routra staci pridat:
```
$router[] = new Route('/api[/v<version>]', 'Api:Api:list');
```
A do configu zaregistrovat servis `Tomaj\NetteApi\Link\ApiLink` (ak este nie je zaregistrovany)
Nasledne sa nam request na url `/api` vrati zoznam zaregistrovanych endpointov a ak zadame v url aj verziu: `/api/v1`, vrati sa len zoznam endpointov zaregistrovanych pre tuto verziu
> List of endpoints (for version)

- src/Misc/ConsoleRequest.php
> FIX: negative values for response time in API web console

- src/Component/ApiConsoleControl.php
- src/Params/InputParam.php
- Valid param always when is not required - also when available values are set
- Changed rendering in API console when available values are set
> Available values changes

- CHANGELOG.md
- src/Misc/ConsoleRequest.php
- src/Params/InputParam.php
- tests/Params/InpuParamTest.php
- tests/Params/ParamsProcessorTest.php
It will be nice to have support for PUT params in handler. So there can be set required/optional and available values.
> Added support for PUT fields

- CHANGELOG.md
- src/Component/ApiConsoleControl.php
- src/Misc/ConsoleRequest.php
Added checkbox to API test console
@tomaj
> Send current PHPSESSID

- src/Params/InputParam.php
Zmena nazvu na POST_JSON_KEY + PSR code style
Více zde: https://github.com/tomaj/nette-api/pull/34
> Added option to accept json params

- CHANGELOG.md
- src/Api.php
- src/ApiDecider.php
- src/Component/ApiListingControl.php
- src/Component/api_listing.latte
- src/HandlerSettings.php
- src/Handlers/ApiListingHandler.php
- src/Link/ApiLink.php
- src/Presenters/ApiPresenter.php
- tests/ApiDeciderTest.php
- tests/Handler/ApiListingHandlerTest.php
- tests/Presenters/ApiPresenterTest.php
Not sure about the naming, but this should replace former array triplet
> Replaced handler information array triplet (endpoint, handler, authorization) with Api

- CHANGELOG.md
- UPGRADE.md
- src/Component/ApiConsoleControl.php
- src/Component/api_listing.latte
- src/Component/console.latte
- src/Handlers/ApiHandlerInterface.php
- src/Handlers/BaseHandler.php
- src/Params/CookieInputParam.php
- src/Params/FileInputParam.php
- src/Params/GetInputParam.php
- src/Params/InputParam.php
- src/Params/JsonInputParam.php
- src/Params/ParamInterface.php
- src/Params/PostInputParam.php
- src/Params/PutInputParam.php
- src/Params/RawInputParam.php
- tests/Authorization/BearerTokenAuthorizationTest.php
- tests/EndpoinIdentifierTest.php
- tests/Handler/EchoHandlerTest.php
- tests/Handler/TestHandler.php
- tests/Handler/TestHandlerTest.php
- tests/Misc/ConsoleResponseTest.php
- tests/Params/ConsoleParamsTest.php
- tests/Params/InpuParamTest.php
> Added attributes to parameters and handlers

- CHANGELOG.md
- src/Component/ApiConsoleControl.php
- src/Misc/ConsoleRequest.php
Resolves #22
Resolves #51 
Resolves #73 
Resolves #76
> Console improvements

- CHANGELOG.md
- composer.json
- src/Handlers/DefaultHandler.php
- src/Handlers/OpenApiHandler.php
- src/Output/AbstractOutput.php
- src/Output/JsonOutput.php
- src/Output/RedirectOutput.php
- src/Params/JsonInputParam.php
- src/Presenters/ApiPresenter.php
- tests/Handler/DefaultHandlerTest.php
Bude mozno pocas pouzivania par veci pofixovat ale je to funkcne
Resolves #49
> Open API handler

- CHANGELOG.md
- README.md
- src/Component/ApiConsoleControl.php
- src/Misc/ConsoleRequest.php
> RESTful urls info + console fix

- CHANGELOG.md
- src/Link/ApiLinkMacro.php
- src/Presenters/ApiPresenter.php
> Detailed error message enabled only for non production mode

- CHANGELOG.md
- README.md
- src/Authorization/BasicAuthentication.php
- src/Authorization/BearerTokenAuthorization.php
- src/Authorization/CookieApiKeyAuthentication.php
- src/Authorization/HeaderApiKeyAuthentication.php
- src/Authorization/QueryApiKeyAuthentication.php
- src/Authorization/TokenAuthorization.php
- src/Component/ApiConsoleControl.php
- src/Handlers/OpenApiHandler.php
- src/Link/ApiLinkMacro.php
- src/Misc/BearerTokenRepositoryInterface.php
- src/Misc/StaticBearerTokenRepository.php
- src/Misc/StaticTokenRepository.php
- src/Misc/TokenRepositoryInterface.php
- src/Output/AbstractOutput.php
- src/Output/RedirectOutput.php
- src/RateLimit/NoRateLimit.php
- src/RateLimit/RateLimitResponse.php
- src/Validation/JsonSchemaValidator.php
- tests/Authorization/BearerTokenAuthorizationTest.php
- tests/Authorization/CookieApiKeyAuthenticationTest.php
- tests/Authorization/HeaderApiKeyAuthenticationTest.php
- tests/Authorization/QueryApiKeyAuthenticationTest.php
- tests/Misc/StaticTokenRepositoryTest.php
- tests/Presenters/ApiPresenterTest.php
- tests/RateLimit/RateLimitResponseTest.php
see https://swagger.io/docs/specification/authentication/api-keys/
cc @ricco24 @mikoczy
> Added API key authentication (query, header, cookie)

- CHANGELOG.md
- src/Component/api_listing.latte
breakIf is not available in if
> Fixed compatibility with latte 2.9.0

- CHANGELOG.md
- src/Params/GetInputParam.php
- src/Params/PostInputParam.php
Resolves https://github.com/tomaj/nette-api/issues/102
> Fix: Handling wrong input for Get and Post InputParam

- CHANGELOG.md
- src/Handlers/OpenApiHandler.php
Resolves: https://github.com/tomaj/nette-api/issues/104
Resolves: https://github.com/tomaj/nette-api/issues/108
> Open API handler fixes

- CHANGELOG.md
- src/Presenters/ApiPresenter.php
This error message would have saved me 2 hours of debugging.
> OutputInterface check in ApiPresenter

- CHANGELOG.md
- src/Handlers/OpenApiHandler.php
- src/Output/RedirectOutput.php
> Fix: Allow yaml format only if symfony/yaml is installed

- CHANGELOG.md
- src/Handlers/OpenApiHandler.php
- src/Misc/ConsoleRequest.php
- src/Params/InputParam.php
- tests/Params/InpuParamTest.php
> Available values with description

- CHANGELOG.md
- src/Handlers/OpenApiHandler.php
> Property with name `type` is now available in json schema

- CHANGELOG.md
- src/Misc/ConsoleRequest.php
Resolves https://github.com/tomaj/nette-api/issues/126
> request url separator

- src/Params/JsonInputParam.php
- tests/Params/InpuParamTest.php
- Ignore bad json schema if are data empty.
- Submit error message if are data required and missing.
> Fix missing json data

- CHANGELOG.md
- src/ApiDecider.php
- src/Handlers/CorsPreflightHandler.php
- src/Handlers/CorsPreflightHandlerInterface.php
Fix multiple service handlers.
> Add CorsPreflightHandlerInterface to enableGlobalPreflight method
